version: "3.8"
services:
  db:
    image: postgres:15.2-bullseye
    restart: always
    environment:
      POSTGRES_DB: vacation_organizer
      POSTGRES_USER: master
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - vacation-organizer-postgres-data:/var/lib/postgres/data

  api:
    build: ./packages/backend
    depends_on:
      - db
    volumes:
      - ./packages/backend:/usr/src/app
    ports:
      - 4000:4000
    restart: always

  client:
    build: ./packages/frontend
    depends_on:
      - api
    volumes:
      - ./packages/frontend:/usr/src/app
    ports:
      - "5173:5173"
    expose:
      - 5173

volumes:
  vacation-organizer-postgres-data:
